//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescoin.Conexion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_NESCOINEntities : DbContext
    {
        public BD_NESCOINEntities()
            : base("name=BD_NESCOINEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Calificacion> Tbl_Calificacion { get; set; }
        public virtual DbSet<Tbl_Ciudad> Tbl_Ciudad { get; set; }
        public virtual DbSet<Tbl_Comuna> Tbl_Comuna { get; set; }
        public virtual DbSet<Tbl_Contacto> Tbl_Contacto { get; set; }
        public virtual DbSet<Tbl_Correo> Tbl_Correo { get; set; }
        public virtual DbSet<Tbl_Direccion> Tbl_Direccion { get; set; }
        public virtual DbSet<Tbl_Forma_Pago> Tbl_Forma_Pago { get; set; }
        public virtual DbSet<Tbl_Log> Tbl_Log { get; set; }
        public virtual DbSet<Tbl_movimiento> Tbl_movimiento { get; set; }
        public virtual DbSet<Tbl_Pais> Tbl_Pais { get; set; }
        public virtual DbSet<Tbl_Profesion> Tbl_Profesion { get; set; }
        public virtual DbSet<Tbl_Telefono> Tbl_Telefono { get; set; }
        public virtual DbSet<Tbl_Tipo_Cuenta> Tbl_Tipo_Cuenta { get; set; }
        public virtual DbSet<Tbl_tipo_log> Tbl_tipo_log { get; set; }
        public virtual DbSet<Tbl_Tipo_usuario> Tbl_Tipo_usuario { get; set; }
        public virtual DbSet<Tbl_Usuario> Tbl_Usuario { get; set; }
        public virtual DbSet<Tbl_Usuario_Correo> Tbl_Usuario_Correo { get; set; }
        public virtual DbSet<Tbl_Usuario_Profesion> Tbl_Usuario_Profesion { get; set; }
        public virtual DbSet<Tbl_Usuario_Telefono> Tbl_Usuario_Telefono { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_tipo_movimiento> Tbl_tipo_movimiento { get; set; }
        public virtual DbSet<Vi_Trae_Vitrina> Vi_Trae_Vitrina { get; set; }
        public virtual DbSet<Vi_Trae_contactos_de_usuario> Vi_Trae_contactos_de_usuario { get; set; }
        public virtual DbSet<Vi_Trae_Oferta_Trabajo> Vi_Trae_Oferta_Trabajo { get; set; }
        public virtual DbSet<Vi_Trae_Presupuesto> Vi_Trae_Presupuesto { get; set; }
        public virtual DbSet<Vi_Trae_Historial> Vi_Trae_Historial { get; set; }
        public virtual DbSet<Vi_Verifica_Presupuesto> Vi_Verifica_Presupuesto { get; set; }
        public virtual DbSet<Vi_Verifica_Solicitud_Presupuesto> Vi_Verifica_Solicitud_Presupuesto { get; set; }
        public virtual DbSet<Vi_Tbl_Echo_Prof_Comuna> Vi_Tbl_Echo_Prof_Comuna { get; set; }
        public virtual DbSet<Tbl_IndicadoresBS> Tbl_IndicadoresBS { get; set; }
    
        public virtual ObjectResult<PA_Trae_Vista_Vitrina_Result> PA_Trae_Vista_Vitrina()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PA_Trae_Vista_Vitrina_Result>("PA_Trae_Vista_Vitrina");
        }
    }
}
