//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescoin.Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Usuario_Profesion
    {
        public decimal id_usuario { get; set; }
        public decimal id_profesion { get; set; }
        public Nullable<double> promedio_calificacion { get; set; }
        public Nullable<bool> estado { get; set; }
        public string descripcion { get; set; }
    
        public virtual Tbl_Profesion Tbl_Profesion { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
