//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescoin.Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_IndicadoresBS
    {
        public decimal id { get; set; }
        public string Objetivos { get; set; }
        public string Metas { get; set; }
        public string Indicador { get; set; }
        public string Iniciativas { get; set; }
    }
}
