//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescoin.Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Log
    {
        public decimal id_log { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<decimal> id_usuario { get; set; }
        public Nullable<decimal> id_tipo_log { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Tbl_tipo_log Tbl_tipo_log { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
