//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescoin.Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_movimiento
    {
        public decimal id_movimiento { get; set; }
        public Nullable<System.DateTime> fecha_movimiento { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> id_usuario { get; set; }
        public Nullable<decimal> id_calificacion { get; set; }
        public string comentario { get; set; }
        public Nullable<decimal> id_forma_pago { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<decimal> id_tipo_movimiento { get; set; }
        public Nullable<decimal> num_ref_movimiento { get; set; }
    
        public virtual Tbl_Calificacion Tbl_Calificacion { get; set; }
        public virtual Tbl_Forma_Pago Tbl_Forma_Pago { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
        public virtual Tbl_tipo_movimiento Tbl_tipo_movimiento { get; set; }
    }
}
