//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescoin.Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Comuna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Comuna()
        {
            this.Tbl_Direccion = new HashSet<Tbl_Direccion>();
        }
    
        public decimal id_comuna { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> id_ciudad { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual Tbl_Ciudad Tbl_Ciudad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Direccion> Tbl_Direccion { get; set; }
    }
}
