//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescoin.Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Contacto
    {
        public decimal id_contacto { get; set; }
        public decimal id_usuario { get; set; }
        public Nullable<decimal> id_tipo_usuario { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<decimal> id_calificacion { get; set; }
        public long num_registro { get; set; }
    
        public virtual Tbl_Calificacion Tbl_Calificacion { get; set; }
        public virtual Tbl_Tipo_usuario Tbl_Tipo_usuario { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
