//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescoin.Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vi_Trae_Historial
    {
        public decimal id_usuario { get; set; }
        public string Titulo { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> id_calificacion { get; set; }
        public long Autonumerico { get; set; }
        public string Tipo_Desc { get; set; }
        public Nullable<System.DateTime> fecha_movimiento { get; set; }
    }
}
