//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescoin.Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vi_Trae_Vitrina
    {
        public decimal id_usuario { get; set; }
        public string nick { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string Profesion { get; set; }
        public string descripcion { get; set; }
        public string foto { get; set; }
        public Nullable<double> promedio_calificacion { get; set; }
    }
}
