//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescoin.Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vi_Tbl_Echo_Prof_Comuna
    {
        public decimal id_comuna { get; set; }
        public string comuna { get; set; }
        public Nullable<decimal> informatica { get; set; }
        public Nullable<decimal> Profesores { get; set; }
        public Nullable<decimal> Mecanica { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
