//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nescoin.Conexion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vi_Verifica_Solicitud_Presupuesto
    {
        public decimal id_movimiento { get; set; }
        public Nullable<decimal> id_tipo_movimiento { get; set; }
        public Nullable<System.DateTime> fecha_movimiento { get; set; }
        public string descripcion { get; set; }
        public string Titulo { get; set; }
        public Nullable<decimal> num_ref_movimiento { get; set; }
        public Nullable<decimal> usuario_logueado { get; set; }
        public Nullable<decimal> id_calificacion { get; set; }
        public string UsuarioSolicita { get; set; }
        public Nullable<long> Autonumerico { get; set; }
    }
}
